import Footer from "./components/Footer";
import Subscribe from "./components/Subscribe";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <Subscribe />
                <Footer />
            </body>
        </html>
    );
}
