import NavMenu from "@/components/NavMenu";
import "./globals.css";
import { Poppins } from "next/font/google";
import Subscribe from "@/components/Subscribe";
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <NavMenu />
                {children}
                <Subscribe />
                <Footer />
            </body>
        </html>
    );
}
